# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-11-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('User_Name', models.CharField(max_length=30)),
                ('Password', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Mobile_No', models.IntegerField()),
            ],
        ),
    ]
